### ISSUE TITLE
Load configuration from file

### ISSUE THREAD

**Issue by ivancorrales** [wesovilabs/goa#5]
It would be handy to provide goa with a mechanism to load configuration from file.

**Comment by ivancorrales** [comment]
goa.yml could look like this

```yaml
output_dir:
skip_dirs:
  - .git
logger:
  level: DEBUG
alias:
  build: go build
  run: go run
  test: go test
```

This file could be generated by just running `goa init` . An a goa.yaml with default values would be created
